# HW 7 - Libraries + Modules
ULAB - Physics and Astronomy Division \
Due **Wednesday, November 6th, 2024 at 11:59pm** on Gradescope

--------------------------------------------------------------

## Module vs. Package vs. Library
### Module
A **module** is a single file containing Python code (typically ending in a `.py` extension) that contains functions and variables. 
- They can be imported into other Python files or notebooks
- You use modules to organize code into smaller, reuseable parts
- Ex: `even_sum.py` that we created during lecture.

*You will create your OWN module for this homework and use that we made during class.*

### Package
A **package** is a group of modules, organized like a directory. 
- A package requires a special `__init__.py` file to tell Python that the ENTIRE directory is something you would like to import.
- Packages can contain sub-pacakges
- Ex: `BAGLE_Microlensing` is an example of a package (if you are in Dex's group, this should be familar to you). Or you could think of `paarti` if you are in Brianna's group.

*You will NOT be working with a package for this homework.*

### Library
A **library** is a much broader term that also refers to a collection of modules (like a package) but a library can also contain mulitple packages. 
- Libraries serve a much wider range of functionality for
- Programmers use packages to have ready-to-go tools that can be used for data manipulation, web development, machine learning or simulations.
- Ex: `numpy` is a very common library. Later in this course we will also be working some of the following libraries `matplotlib`, `scipy`, and `astropy`, `pandas`, etc

*You WILL be working with the extensive numpy library for this homework!*

--------------------------------------------------------------

# 1 NumPy
**NumPy** (aka Numerical Python) is a library that was designed for caring out computations in Python. 

We did not have a ton of time to work through examples during class, so I will ask that you check out this website for more information: https://numpy.org/doc/ 

Before we can work through any problems, you need to call the following in your notebook:

In [25]:
import numpy as np

## 1.1 Lists vs. Arrays
*When I first started working with NumPy I didn't understand what was so special about arrays. This homework problem should help illustrate the difference. Make sure to follow each step and follow good coding practices.*

1) Make a list called `my_list` and make an array called `my_arr` with the same values. There is an example below, but don't copy mine! Ex:
```
my_list = [11, 12, 13, 14, 15]
my_arr = np.array([11, 12, 13, 14, 15])
```
*Notice that to use the `numpy` package we had to call its short cut `np` and then call upon its funciton `.array()`. This is similar to working with a built-in python function like `.append()`.*

In [9]:
my_list = [2,4,6,8,10,12]
my_arr = np.array([2,4,6,8,10,12])

2) Multiply `my_list` by 4 and multiply `my_arr` by 4. Print the results. Describe what happens in a comment.

In [13]:
print(my_list*4)
print(my_arr*4)
# my_list repeats itself four times while my_arr has its values multiplied by 4

[2, 4, 6, 8, 10, 12, 2, 4, 6, 8, 10, 12, 2, 4, 6, 8, 10, 12, 2, 4, 6, 8, 10, 12]
[ 8 16 24 32 40 48]


3) Add `my_list` with `my_list`. Add `my_arr` with `my_arr`. Add `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [17]:
print(my_list + my_list)
print(my_arr + my_arr)
print(my_list + my_arr)
# adding my list together puts another my list at the end of the original list. Adding my_arr with either my_arr or my_list actually adds the values together.

[2, 4, 6, 8, 10, 12, 2, 4, 6, 8, 10, 12]
[ 4  8 12 16 20 24]
[ 4  8 12 16 20 24]


4) Subtract `my_list` with `my_list`. Subtract `my_arr` with `my_arr`. Subtract `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [25]:
print(my_list - my_list)
print(my_arr - my_arr)
print(my_list - my_arr)
# it doesn't let you subtract my_list from my_list (not an operation you can use on lists). For the array tho it subtracts the values from eachother and since they're the same you're left with zeroes.

TypeError: unsupported operand type(s) for -: 'list' and 'list'

5) Multiply `my_list` with `my_list`. Multply `my_arr` with `my_arr`. Multiply `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [33]:
print(my_arr*my_arr)
print(my_list*my_arr)
print(my_list*my_list)
# Multipling with an array multiplies each value by the value in the other array/list. It doesn't let you multiply two lists together.

[  4  16  36  64 100 144]
[  4  16  36  64 100 144]


TypeError: can't multiply sequence by non-int of type 'list'

7) Divide `my_list` with `my_list`. Divide `my_arr` with `my_arr`. Divide `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [39]:

print(my_arr/my_arr)
print(my_list/my_arr)
print(my_list/my_list)
# Dividing the array by the array/list leaves you with ones since they have the same values while for the list it doesn't let you divide lists.

[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]


TypeError: unsupported operand type(s) for /: 'list' and 'list'

8) After working through this problem, in at least two sentences, describe the difference between a list and an array.

In [43]:
# Lists and arrays can both store integers, however they function differently when operators are used. Using operators on an array will apply this change to each value in the array whereas for a list it will either not work or it will add itself to the end of the list.

## 1.2 Nested List and Multi-Dimensional Arrays
A **nested list** is when you have a list as an element for a list. Example:
```
nested_list = [[1, 2, 3], [4, 5, 6]]
```

A **multi-dimensional array** is essentially a nested list, but it contains the properties of a matrix. Example:
```
multi_d_array = np.array([[1, 2, 3], [4, 5, 6]])
```

Go to this website for more information on NumPy: https://www.w3schools.com/python/numpy/default.asp

Write a **function** that takes in a two-dimensional array. Example:

```
arr3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
```

and then returns the second value in each row. Example:

```
[4, 10, 16]
```

In [73]:
def second_value_in_row(arr):
    # Go through the given 2d array and return an array taking the second value in each row
    second_value = arr[0:len(arr), 1]
    return second_value

arr3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
print(second_value_in_row(arr3))

[ 4 10 16]


In 2-3 sentences, describe what section of the website helped you write your function. 

In [ ]:
# The section about numpy array indexing helped me understand how to access values in the array. The section about array slicing helped me understand how to go through the array and get the values I wanted.

How would you take a nested list and return the second value in each row? Explain in 2-3 sentences and show an example.

## 1.3 Up to You!
With the website I just gave you: https://www.w3schools.com/python/numpy/default.asp

I recommend working through the examples they provide (you don't have to do all of them, but a few would be good). It will help you build an intuition for numpy. It won't take very long, there are only a couple of examples per section.

Write you own **function** that follows the theme of one of the sections (i.e. array reshaping, array filter, random intro, etc). For example, if you are curious about the section "**NumPy Creating Arrays**" you could write a function that creates a multi-dimensional array.

```

>>> def make_multi_dimensional_array(one_d_array, dimensions):
...     # Creates a multi-dimensional array
...     # Your code here
...     return # Your code here

>>> my_one_d_array = [2, 4, 6, 8]
>>> my_dimension = 10
>>> ten_d_array = make_multi_dimensional_array(my_one_d_array, my_dimension)
>>> print(ten_d_array)
[[[[[[[[[[2 4 6 8]]]]]]]]]]

```

Your function should be more detailed than the example I gave you. Include at least one of the following: 
- a conditional statement
- an assignment operator
- a loop (`for` or `while`)
- `if`, `elif`, `else`, statement

In [389]:
def reshape_into_3D(arr, x_dimension, y_dimension, z_dimension):
    # Reshapes a 1D array into a 3D array, but first checks to see if there's the right number of elements.
    #If there's too many elements it will cut out odd indexed elements until there's enough.
    #If there's too little elements it will add 0s to fill remaining elements.

    num_of_elements = x_dimension*y_dimension*z_dimension
    newarr = arr
    if num_of_elements == len(newarr):
        newarr.reshape(x_dimension, y_dimension, z_dimension)
    elif num_of_elements < len(newarr):
        i = 1
        while i < len(newarr) and num_of_elements < len(newarr):
            newarr = np.delete(newarr,i)
            i += 2
        newarr.reshape(x_dimension, y_dimension, z_dimension)
    else:
        i = len(newarr)
        while i < num_of_elements:
            newarr = np.append(newarr, 0)
            i +=1
        newarr.reshape(x_dimension, y_dimension, z_dimension)
    return newarr

In the section you took inspiration from, show all of the examples below. Follow good coding practices and give at least two test cases for each example. Don't forget comments! \
\
*For my example, I took inspiration from **NumPy Creating Arrays** so I would show following examples with DIFFERENT test cases: Create a NumPy ndarray Object, Dimensions in Arrays ,0-D Arrays, 1-D Arrays, 2-D Arrays, 3-D Arrays, Check Number of Dimensions, Higher Dimensional Arrays.*

In [363]:
# Reshape 1D into 2D
arr = np.array([2,4,6,8,10,12])
newarr = arr.reshape(2,3)
print(newarr)

# Reshape 1D into 3D
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

# Cheking if array is a copy/view
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

# Using unkown dimension
arr = np.array([2,4,6,8,10,12,14,16])
newarr = arr.reshape(2,2,-1)
print(newarr)

# flattening arrays
newarr = newarr.reshape(-1)
print(newarr)

[[ 2  4  6]
 [ 8 10 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[1 2 3 4 5 6 7 8]
[[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]
[ 2  4  6  8 10 12 14 16]


In 2-3 sentences, describe how your function took inspiration from a section.\
\
*For my example, `make_multi_dimensional_array`, I would talk about the **NumPy Creating Arrays** section and how I took inspiration from the example **Higher Dimensional Arrays**.*

In [365]:
# I took inspiration from the section of reshaping 1D arrays into 3D arrays because that's the primary thing my function does. I also took inspiration from the section about wether you can reshape an array into any size array and wrote my function to account for that.

# 2 Brianna's Module
During lecture we created and worked with a module called `even_sum.py`. Import that module here. 

In [7]:
import even_sum as es

Now that you have imported the module. Call the module and the first function with your own list of numbers. 

In [13]:
numbers = [1,2,3,4,5]
print(es.sum_even_numbers(numbers))

6


I have provided you a separate module called `example.py`. Import that module here.

In [10]:
import example

With the following variables, use my module to show which of the rocket's escape!

In [27]:
rocket_velocities = np.array([
    [1000, 5000, 8000, 12000],  # Rocket 1's velocity at different times
    [2000, 6000, 9000, 10000],  # Rocket 2
    [3000, 3100, 3200, 3300]    # Rocket 3
])

mass_of_planet = 5.972e24 # kilograms
radius_of_planet = 6.371e6 # meters

In [29]:
print(example.rocket_launch(rocket_velocities, mass_of_planet, radius_of_planet))

['Rocket left the planet!', 'Rocket is orbiting around the planet.', 'Rocket crashes back into the planet!']


In 2-3 sentences describe how this code follows "good coding practices" and where there is room for improvement.

In [37]:
# All of the functions have clear variable names that tell you what to expect an also have comments under the function telling you what they do. There could be some room for improvement on the detail of the comment for rocket_launch since it doesn't explain how it will determine if the rocket can escape.

# 3 Your Turn!
Now its your turn to make a module! Choose a topic from a class (could be physics, computer science, nuclear engineering, biology, astronomy, math, or an topic that interests you!) and build a module around it! Look at my module called `example.py` and base your structure around it. Your module NEEDS to include the following.

Overall:
1) Your module needs to use at least one NumPy function: https://numpy.org/devdocs/reference/routines.math.html
2) Your module needs to contain a multi-dimensional array: https://numpy.org/devdocs/reference/arrays.ndarray.html 
3) Your module needs **at least** three functions that follow good coding practices.
4) Inside your function, include comments. Don't forget to describe what the function is doing and what the inputs and outputs are.
5) Your module needs either a `for` loop or `while` loop.
6) Your module needs an `if`, `elif`, and `else` statement.
7) Your module needs at least two assignment variables (`+=`, `*=`, etc).
8) Creativity. *If it looks like you plugged this whole thing into ChatGPT, I will take off points. You can use ChatGPT to help you code, but you can't use it to just do your homework for you. That's no fun :(*

In 2-3 sentences, describe the topic of your module and its capabilities. 

In [ ]:
# My module is based around the 3n+1 conjecture (multiply odd numbers by 3 and add one and divide even numbers by 2). The module has a function that can take in an array of numbers and a limit to the number of operations used and check to see if within ths number of operations a number will eventually loop to the number 1. 

In 2-3 sentences, answer the following. What was the most challenging part of building this module? What did you learn in the process that you can apply to future coding assignments?

In [353]:
# My last function keeps returning none. I fiddled around with it for an hour but honestly can't figure out what's making it go wrong. In that sense I learned that things won't always work out and it feels pretty frustrating.

Once your module is complete, import it here.

In [349]:
import three_n_plus_one as three_n

Call each of your functions in the cell below. Make sure to show the outputs! 

In [355]:
number = 23
new_number = three_n.one_iteration_of_3n_plus_one(number)
print(new_number)
loop_of_number = three_n.array_of_3n_plus_one_loop(number, 15)
print(loop_of_number)

numbers = [1,46,47,3,24,7,53,23]
operation_limit = 20
numbers_loop, successes = three_n.bounded_3n_plus_one(numbers, operation_limit)
print(numbers_loop)

70
[ 23.  70.  35. 106.  53. 160.  80.  40.  20.  10.   5.  16.   8.   4.
   2.   1.]


TypeError: cannot unpack non-iterable NoneType object

# 4 Proper Submission
To recieve full credit for this assignment make sure you do the following:

1) Copy this homework assignment from the `ulab_2024` repository into **YOUR** local `homework7` branch. It will contain this notebook and an additional file called `example.py`. 
   
2) Follow the tasks. Make sure to run all the cells so that **all** output is visible. You will get points taken off if your ouputs are not shown!

3) Add/commit/push this notebook and **ANY** modules (so you should have `example.py` and your module) used in this homework assignment to your remote `homework7` branch. Make sure to have NOTHING else in your branch (i.e. no previous homeworks or lecture notes).

4) Do the following:
- Take a screenshot of moving **into or out** of your `homework7` brach, call it `hw7_branch`.
- Take a screenshot of calling `ls` in your `homework7` branch, it should only contain items relevent to homework 7, call it `hw7_ls`.
- Take a screenshot of adding this assignment to your local `homework7` branch, call it `hw7_add`.
- Take a screenshot of committing this assignment to your local `homework7` branch, call it `hw7_commit`.
- Take a screenshot of pushing this assignment to your remote `homework7` branch, call it `hw7_push`. 

6) Include these screenshots in your `homework7` branch. Upload your `homework7` branch to Gradescope!